version: '3'

services:
  web:
    build: ./backend
    ports: ['5000:5000']
    volumes: ['./backend:/app']
    depends_on:
      - mongo
    networks:
      - medusanet
  mongo:
    image: mongo:4.0.3
    ports: ['3001:27017']
    volumes:
      - ./db:/data/db
    networks:
      medusanet:
        aliases:
          - "medusadb"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: ['./app:/app']
    ports:
      - '3000:3000'
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
    networks:
      - medusanet
networks:
  medusanet:
    driver: bridge